### ISSUE TITLE
[FEATURE-REQUEST] Ability to use the function from the command line

### ISSUE THREAD

**Issue by squgeim** [pratishshr/bharyang#1]
Proposal:

- The core could be a command line application
- Either, Take input selection from standard input and write the output to standard output
- Or, take the input as file and write output as file
- Or, take the location of the file to edit with the selection line number range and edit the file in-place

This would make it possible to use the same core to write extensions for multiple text editors that may not use javascript as the language for their extensions.

**Comment by squgeim** [comment]
I have implemented a CLI version from this core and a plugin for vim as well.

CLI:
https://github.com/squgeim/bharyang-cli

VIM:
https://github.com/squgeim/bharyang-vim

**Comment by pratishshr** [comment]
@squgeim This is great. I'll add it to the README file. 👍 😃
